name: chat_programming_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.7.1
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.20.3
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  gap: ^3.0.0
  hooked_bloc: ^1.4.1
  injectable: ^2.1.1
  logger: ^2.0.2+1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  mocktail: ^1.0.1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.2.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true